// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szwbjytdaaxcdyewfqwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6d2JqeXRkYWF4Y2R5ZXdmcXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzA5MjMsImV4cCI6MjA3MjEwNjkyM30.Diq07Av5OslosR1wSg1GQGyHEgFhLnmXvCXrK8oC1Ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});